#!/bin/zsh

# CONFIGS
# --------------------
COMPLETION_WAITING_DOTS="true"
DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="false"
HYPHEN_INSENSITIVE="true"

# ENVIRONMENT
# --------------------
# export ZSH=$HOME/.oh-my-zsh
export ZSH=$HOME/.zshrc
export LANG=en_US.UTF-8
export TERM=xterm-256color

# PLUGINS
# --------------------
plugins=(
  git
  zsh-autosuggestions
)

# SOURCE
# --------------------
# source $ZSH/oh-my-zsh.sh
# source $ZSH/zsh-autosuggestions/zsh-autosuggestions.zsh
# CONDITIONAL
if [ -e zshiardo.zsh ]; then source zshiardo.zsh; fi
